### ISSUE TITLE
[Question] Removing components?

### ISSUE THREAD

**Issue by mlange-42** [unitoftime/ecs#32]
Hi @unitoftime!

I would like to include your ECS in my comparative benchmarks over on [mlange-42/arche](https://github.com/mlange-42/arche).

Iteration performance looks very promising. However, could it be that there is no way to remove components from entities, or am I missing something?

Also, it is not really clear to me how to use `Write` on entities that already have some components. The code looks to me like all existing components of the entity are removed, and replaced by the new ones.

Thanks!

EDIT: FYI, the numbers for a simple pos/vel benchmark:

```
BenchmarkIterArche-4           	  447373	      2663 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterArche-4           	  426343	      2756 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterArche-4           	  421489	      2759 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterArche-4           	  426030	      2788 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterArche-4           	  436239	      2725 ns/op	       0 B/op	       0 allocs/op
BenchmarkBuildArche-4          	    1470	    849158 ns/op	 2732843 B/op	   10258 allocs/op
BenchmarkBuildArche-4          	    1310	    889325 ns/op	 2732841 B/op	   10258 allocs/op
BenchmarkBuildArche-4          	    1378	    895151 ns/op	 2732839 B/op	   10258 allocs/op
BenchmarkBuildArche-4          	    1316	    922162 ns/op	 2732840 B/op	   10258 allocs/op
BenchmarkBuildArche-4          	    1233	    919672 ns/op	 2732839 B/op	   10258 allocs/op
-------------------------------------------------------------------------------------------------------------
BenchmarkIterUot-4             	  345000	      3440 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterUot-4             	  348829	      3435 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterUot-4             	  344227	      3478 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterUot-4             	  348615	      3438 ns/op	       0 B/op	       0 allocs/op
BenchmarkIterUot-4             	  344654	      3481 ns/op	       0 B/op	       0 allocs/op
BenchmarkBuildUot-4            	     679	   1743690 ns/op	 2068169 B/op	   11142 allocs/op
BenchmarkBuildUot-4            	     685	   1747921 ns/op	 2068181 B/op	   11142 allocs/op
BenchmarkBuildUot-4            	     684	   1746020 ns/op	 2068181 B/op	   11142 allocs/op
BenchmarkBuildUot-4            	     682	   1742733 ns/op	 2068181 B/op	   11142 allocs/op
BenchmarkBuildUot-4            	     686	   1742746 ns/op	 2068179 B/op	   11142 allocs/op
```

So, compared to [go-gameengine-ecs](https://github.com/marioolofo/go-gameengine-ecs), [Donburi], [Ento](https://github.com/wwfranczyk/ento) and [Entitas-Go](https://github.com/Falldot/Entitas-Go), you are my most serious "competitor". 👍

**Comment by unitoftime** [comment]
Cool!

Yeah funnily enough, there actually isn't a way to delete individual components. That's only because I haven't really needed it in the game I'm making. Structurally it's very similar to adding new components, though, so I don't mind adding it if you need it for your benchmark (I probably would have added it at some point in the future anyways).

The `Write` function should work as intended: It'll rewrite the archetype if a new component type is added. It does that by copying components "out" of the old archetype. then pasting them "in" to the new archetype. So with the `Write` API, you can just do this:

```
id := world.NewId()
ecs.Write(world, id, ecs.C(Position{1, 2, 3}))
ecs.Write(world, id, ecs.C(Velocity{4, 5, 6}))
```
After that you should have an entity at `id` with both the `Position` and `Velocity`

You can also veriadically write both components simultaneously:
```
id := world.NewId()
ecs.Write(world, id, ecs.C(Position{1, 2, 3}), ecs.C(Velocity{4, 5, 6}))
```

I'll add the component removal function and get back to you when it's done. Feel free to let me know if you have any other questions.

Thanks!

**Comment by unitoftime** [comment]
Hi again,

I went ahead and added a function `ecs.DeleteComponent` that you can use for individual component deletions in your benchmark. It's likely not very fast, but at least its available now.

Curious to see the final benchmarks and code. Let me know if you need anything else.

Thanks!

**Comment by mlange-42** [comment]
Thanks a lot!

The code for the simple and all but comprehensive benchmarks is in PR mlange-42/arche#311

Plots for the results below, or in the [README on the resp. branch](https://github.com/mlange-42/arche/tree/benchmark-unitoftime-ecs#benchmarks)

In case you have any suggestions for improving the code, please share them.
Looks like the new function for removing components is indeed quite slow. 😄 If you improve it, please let me know and I will re-run the benchmarks.

![Benchmark vs. Go ECSs - Pos/Vel](https://github.com/mlange-42/arche/assets/44003176/7b73f9d8-238c-4d7a-98a1-267ad0b5e4a8)  
*Position/Velocity benchmarks of Arche (left-most) vs. other Go ECS implementations.
Left panel: query iteration (log scale), right panel: world setup and entity creation.*
</div>

![Benchmark vs. Go ECSs - Add/remove](https://github.com/mlange-42/arche/assets/44003176/7a127568-e71a-441f-91b0-6e626b3fcf19)  
*Add/remove component benchmarks of Arche (left-most) vs. other Go ECS implementations.
Left panel: iteration, right panel: world setup and entity creation.*
</div>

**Comment by unitoftime** [comment]
Cool, Glad it worked for your benchmark! Yeah I was kinda expecting it to be slow lol. I think once iterators come out I might take another pass at API changes and performance optimizations. I'll let you know!

Thanks!
